import fs from 'node:fs/promises';
import path from 'node:path';

import YAML from 'yaml';
import { ok, err, type Result } from 'neverthrow';
import { Compile } from 'typebox/compile';
import type { TLocalizedValidationError } from 'typebox/error';
import type { ContractRegistryCache } from '@rawbox/plugin/core';

import {
  RawboxLock,
  RAWBOX_LOCK_FILENAME,
  RAWBOX_LOCK_VERSION,
  type RawboxLockEntry,
} from './lock-types.js';
import {
  CONTRACT_REGISTRY_SUBPATH,
  loadPluginContractRegistry,
  type PluginRegistryLoadFailure,
} from './plugin-registry-loader.js';
import { getErrorMessage } from '../utils/error.js';

// ---------------------------------------------------------------------------
// rawbox.lock — read, write, resolve, verify
//
// The workflow is the manifest and is *never* rewritten; this generated sibling
// file is the lock. It lives next to `workspace.yaml`, is keyed by package name
// at the workspace level, and records for each package the version npm resolved
// plus the contract-registry hash that version produced.
//
// Three rules the rest of the system depends on:
//   - an absent lock means "resolve whatever is installed" — no integrity
//     guarantee, which is the convenient development default;
//   - an absent *entry* in a present lock is treated the same way, so a
//     partially locked workspace stays usable;
//   - a present entry that disagrees with the installed package is a hard
//     error naming the package and the remedy.
// ---------------------------------------------------------------------------

const lockValidator = Compile(RawboxLock);

/** Subpath every Rawbox plugin must export to expose its `ContractRegistry`. */
const REGISTRY_SUBPATH = `./${CONTRACT_REGISTRY_SUBPATH}`;

/** `resolved:` value used when a package ships no readable `version`. */
const UNKNOWN_VERSION = 'unknown';

const LOCK_FILE_HEADER = [
  '# rawbox.lock — generated by `rawbox-cli workflow lock`. Do not hand-edit.',
  '#',
  '# Keyed by package name at the *workspace* level, so workflows sharing a',
  '# plugin share one entry. `resolved` is the version that was installed;',
  '# `registryHash` is the contract-registry hash that version produced.',
  '# Re-run `rawbox-cli workflow lock <workflow file>` after any contract',
  '# change in a dependency.',
  '',
].join('\n');

/** Absolute path of the lock file for a workspace directory. */
export function rawboxLockPath(workspaceDir: string): string {
  return path.join(path.resolve(workspaceDir), RAWBOX_LOCK_FILENAME);
}

// ---------------------------------------------------------------------------
// Resolution: package name → installed version + contract-registry hash
// ---------------------------------------------------------------------------

/** What resolving one declared package yields. */
export interface ResolvedPluginLockEntry {
  /** The package name, i.e. the `plugins:` key and the lock key. */
  name: string;
  /** The version npm actually installed, or `"unknown"` when unreadable. */
  resolved: string;
  /** SHA-256 hash of the loaded contract registry. */
  registryHash: string;
  /** Absolute path of the contract-registry module that was loaded. */
  registryPath: string;
  /**
   * Set when this plugin's own resolved `typebox` differs from the
   * framework's — see `typebox-compat.ts`. Reported as context only; the
   * package still resolved and hashed successfully, and this is not a reason
   * this entry failed.
   */
  typeboxVersionNote?: string;
}

/**
 * Reads the installed package's `version` by walking up from the resolved
 * registry module to the nearest `package.json` that names the package.
 *
 * `require.resolve('<pkg>/package.json')` cannot be used: Node's exports
 * encapsulation blocks any deep import a package's `exports` map does not
 * list, and `./package.json` is almost never listed — least of all by Rawbox
 * plugins, which are required to declare `exports`.
 */
async function readInstalledVersion(
  registryPath: string,
  packageName: string,
): Promise<string> {
  let dir = path.dirname(registryPath);

  for (;;) {
    try {
      const raw = await fs.readFile(path.join(dir, 'package.json'), 'utf-8');
      const pjson = JSON.parse(raw) as { name?: unknown; version?: unknown };
      if (pjson.name === packageName) {
        return typeof pjson.version === 'string' && pjson.version.length > 0
          ? pjson.version
          : UNKNOWN_VERSION;
      }
    } catch {
      // No readable package.json at this level — keep walking up. A plugin's
      // registry usually sits under `dist/`, so at least one hop is normal.
    }

    const parent = path.dirname(dir);
    if (parent === dir) return UNKNOWN_VERSION;
    dir = parent;
  }
}

/**
 * Renders a shared-loader failure as the sentence locking should print.
 *
 * The wording is locking's own: it always names the package, what was looked
 * for, where, and the single next action that fixes it. `workflow verify` and
 * the runner phrase the same three failures differently because their next
 * action differs, which is why the loader hands back structured failures rather
 * than prose.
 */
function describeLockFailure(
  failure: PluginRegistryLoadFailure,
  resolveFromDir: string,
): string {
  switch (failure.kind) {
    case 'unresolved':
      return (
        `Plugin "${failure.packageName}" could not be resolved from "${path.resolve(resolveFromDir)}".\n` +
        `  Looked for: ${failure.specifier}\n` +
        `  ${failure.cause ?? `Cannot find module '${failure.specifier}'`}\n` +
        `  Install the workspace's plugins first: npx rawbox-cli workspace setup <workspace file> [target folder]`
      );
    case 'import-failed':
      return (
        `Plugin "${failure.packageName}" resolved to "${failure.registryPath}" but its contract registry could not be imported.\n` +
        `  ${failure.cause}\n` +
        `  Build the plugin (npm run build) and retry.` +
        (failure.typeboxVersionNote ? `\n  Note: ${failure.typeboxVersionNote}` : '')
      );
    case 'not-a-registry':
      return (
        `Plugin "${failure.packageName}" resolved to "${failure.registryPath}", but that module has no default export ` +
        `carrying a "contractRecord".\n` +
        `  A Rawbox plugin must default-export the registry built by setupContractRegistry ` +
        `from its "${REGISTRY_SUBPATH}" entry point.`
      );
  }
}

/**
 * Resolves every declared package against `resolveFromDir`, loads its contract
 * registry, and pairs the installed version with the registry's hash.
 *
 * Resolution, import and hashing are {@link loadPluginContractRegistry}, shared
 * with `PluginDiscoverer.loadPlugins` and `workflow verify`. Two things stay
 * here because they are locking's alone:
 *
 *   - the **bare-specifier fallback stays off**. A lock answers "what is
 *     installed in *this* workspace", so falling back to whatever the runner's
 *     own dependency tree happens to hold would record a wrong answer instead
 *     of reporting a missing one;
 *   - every failure is collected rather than thrown on the first one, and the
 *     batch fails as a whole: the author is fixing an install, and one pass
 *     should surface the whole list. `plugin info` therefore calls this **once
 *     per package** — a batch `err` discards the entries that did resolve,
 *     which is right for locking and wrong for a per-package report.
 *
 * @param packageNames - Keys of the workflow's `plugins:` map.
 * @param resolveFromDir - Directory whose `node_modules` chain resolution starts
 *   from; normally the workspace directory.
 * @param registryCache - Optional cache to populate as a side effect, so a
 *   caller that also needs the registries does not import them twice.
 */
export async function resolvePluginLockEntries(
  packageNames: readonly string[],
  resolveFromDir: string,
  registryCache?: ContractRegistryCache,
): Promise<Result<ResolvedPluginLockEntry[], string>> {
  const entries: ResolvedPluginLockEntry[] = [];
  const failures: string[] = [];

  for (const name of packageNames) {
    const result = await loadPluginContractRegistry(name, {
      resolveFrom: [resolveFromDir],
      ...(registryCache ? { registryCache } : {}),
    });

    if (result.isErr()) {
      failures.push(describeLockFailure(result.error, resolveFromDir));
      continue;
    }

    // Guaranteed: the fallback is off, so a resolved path always came back.
    const registryPath = result.value.registryPath as string;

    entries.push({
      name,
      resolved: await readInstalledVersion(registryPath, name),
      registryHash: result.value.registryHash,
      registryPath,
      ...(result.value.typeboxVersionNote === undefined
        ? {}
        : { typeboxVersionNote: result.value.typeboxVersionNote }),
    });
  }

  if (failures.length > 0) {
    return err(failures.join('\n\n'));
  }

  return ok(entries);
}

/** Package name → registry hash, the mapping `resolveWorkflow` takes. */
export function toRegistryHashByPlugin(
  entries: readonly ResolvedPluginLockEntry[],
): Record<string, string> {
  const map: Record<string, string> = {};
  for (const entry of entries) {
    map[entry.name] = entry.registryHash;
  }
  return map;
}

// ---------------------------------------------------------------------------
// Read / write
// ---------------------------------------------------------------------------

/**
 * Reads `<workspaceDir>/rawbox.lock`.
 *
 * A missing file resolves to `ok(undefined)` — that is "resolve whatever is
 * installed", not an error. A file that exists but does not parse or
 * does not validate *is* an error: a corrupt lock must never be silently
 * downgraded to "unlocked", because that turns an integrity failure into a
 * successful run.
 */
export async function readRawboxLock(
  workspaceDir: string,
): Promise<Result<RawboxLock | undefined, string>> {
  const lockPath = rawboxLockPath(workspaceDir);

  let content: string;
  try {
    content = await fs.readFile(lockPath, 'utf-8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return ok(undefined);
    }
    return err(`Failed to read "${lockPath}": ${getErrorMessage(error)}`);
  }

  let document: unknown;
  try {
    // YAML is a superset of JSON here, so one parser accepts both the document
    // this module writes and a hand-written JSON one.
    document = YAML.parse(content);
  } catch (error) {
    return err(
      `Failed to parse "${lockPath}": ${getErrorMessage(error)}\n` +
        `The lock is generated — regenerate it with: npx rawbox-cli workflow lock <workflow file>`,
    );
  }

  if (!lockValidator.Check(document)) {
    const details = Array.from(lockValidator.Errors(document))
      .map(
        (error: TLocalizedValidationError) =>
          `  - Path: "${error.instancePath}" : ${error.message}`,
      )
      .join('\n');
    return err(
      `"${lockPath}" is not a valid rawbox.lock (expected version "${RAWBOX_LOCK_VERSION}"):\n${details}\n` +
        `The lock is generated — regenerate it with: npx rawbox-cli workflow lock <workflow file>`,
    );
  }

  return ok(document);
}

/**
 * Writes `<workspaceDir>/rawbox.lock`.
 *
 * Package keys are sorted so the file is byte-stable across runs: a lock that
 * reordered itself on every invocation would produce noise in every diff and
 * would make "did locking change anything?" unanswerable.
 */
export async function writeRawboxLock(
  workspaceDir: string,
  lock: RawboxLock,
): Promise<Result<string, string>> {
  const lockPath = rawboxLockPath(workspaceDir);

  const plugins: Record<string, RawboxLockEntry> = {};
  for (const name of Object.keys(lock.plugins).sort()) {
    // Guarded: `name` comes from `Object.keys(lock.plugins)`.
    plugins[name] = lock.plugins[name] as RawboxLockEntry;
  }

  const document: RawboxLock = { version: lock.version, plugins };

  try {
    await fs.mkdir(path.dirname(lockPath), { recursive: true });
    await fs.writeFile(
      lockPath,
      `${LOCK_FILE_HEADER}${YAML.stringify(document)}`,
      'utf-8',
    );
  } catch (error) {
    return err(`Failed to write "${lockPath}": ${getErrorMessage(error)}`);
  }

  return ok(lockPath);
}

// ---------------------------------------------------------------------------
// Verification
// ---------------------------------------------------------------------------

/**
 * Checks a lock against what is actually installed.
 *
 * Only packages present in *both* the lock and the supplied map are compared:
 * a package with no lock entry is unlocked by definition, and a package the
 * caller did not load is a separate diagnostic that belongs to whoever tried
 * to load it.
 *
 * @param lock - Parsed lock contents, or `undefined` for "no lock" (always ok).
 * @param registryHashByPlugin - Package name → hash of the installed registry.
 * @param packageNames - Restricts the check to these packages; defaults to
 *   every package in the lock.
 */
export function verifyRawboxLock(
  lock: RawboxLock | undefined,
  registryHashByPlugin: Readonly<Record<string, string>>,
  packageNames?: readonly string[],
): Result<void, string> {
  if (!lock) return ok(undefined);

  const names = packageNames ?? Object.keys(lock.plugins);
  const mismatches: string[] = [];

  for (const name of names) {
    const entry = lock.plugins[name];
    const installed = registryHashByPlugin[name];
    if (!entry || installed === undefined) continue;

    if (entry.registryHash !== installed) {
      mismatches.push(
        `rawbox.lock mismatch for plugin "${name}".\n` +
          `  locked   : ${entry.registryHash} (resolved version ${entry.resolved})\n` +
          `  installed: ${installed}\n` +
          `The installed package's contracts differ from the ones that were locked, so every ` +
          `step referencing "${name}" is bound to a registry that no longer exists.\n` +
          `Re-lock with: npx rawbox-cli workflow lock <workflow file>`,
      );
    }
  }

  if (mismatches.length > 0) {
    return err(mismatches.join('\n\n'));
  }

  return ok(undefined);
}

// ---------------------------------------------------------------------------
// Orchestration
// ---------------------------------------------------------------------------

/** Inputs to {@link lockWorkspacePlugins}. */
export interface LockWorkspacePluginsOptions {
  /** Directory holding `workspace.yaml`; the lock is written here. */
  workspaceDir: string;
  /** Package names to lock — the keys of a workflow's `plugins:` map. */
  packageNames: readonly string[];
  /**
   * Directory to resolve packages from. Defaults to `workspaceDir`, which is
   * where `workspace setup` installs them.
   */
  resolveFromDir?: string;
  /** Optional cache populated with every registry that was loaded. */
  registryCache?: ContractRegistryCache;
}

/** What {@link lockWorkspacePlugins} produced. */
export interface LockWorkspacePluginsResult {
  /** The lock as written, including entries carried over from other workflows. */
  lock: RawboxLock;
  /** Absolute path of the written file. */
  lockPath: string;
  /** The entries this call resolved, in `packageNames` order. */
  entries: ResolvedPluginLockEntry[];
  /** Package names whose entry changed or was added by this call. */
  changed: string[];
}

/**
 * Resolves every named package, merges the results into the workspace's
 * existing lock, and writes it.
 *
 * Merging rather than replacing is what makes the workspace-level key work: the
 * command takes *one* workflow, but the lock serves every workflow in the
 * workspace, so overwriting would silently unlock the siblings. Entries for
 * packages this workflow does not declare are carried through untouched.
 *
 * The workflow file is not read, written, or otherwise involved — the caller
 * supplies only the package names it parsed out.
 */
export async function lockWorkspacePlugins(
  options: LockWorkspacePluginsOptions,
): Promise<Result<LockWorkspacePluginsResult, string>> {
  const { workspaceDir, packageNames, registryCache } = options;
  const resolveFromDir = options.resolveFromDir ?? workspaceDir;

  const existingResult = await readRawboxLock(workspaceDir);
  if (existingResult.isErr()) {
    return err(existingResult.error);
  }
  const existing = existingResult.value;

  const resolvedResult = await resolvePluginLockEntries(
    packageNames,
    resolveFromDir,
    registryCache,
  );
  if (resolvedResult.isErr()) {
    return err(resolvedResult.error);
  }
  const entries = resolvedResult.value;

  const plugins: Record<string, RawboxLockEntry> = { ...(existing?.plugins ?? {}) };
  const changed: string[] = [];

  for (const entry of entries) {
    const previous = plugins[entry.name];
    const next: RawboxLockEntry = {
      resolved: entry.resolved,
      registryHash: entry.registryHash,
    };
    if (
      !previous ||
      previous.registryHash !== next.registryHash ||
      previous.resolved !== next.resolved
    ) {
      changed.push(entry.name);
    }
    plugins[entry.name] = next;
  }

  const lock: RawboxLock = { version: RAWBOX_LOCK_VERSION, plugins };

  const writeResult = await writeRawboxLock(workspaceDir, lock);
  if (writeResult.isErr()) {
    return err(writeResult.error);
  }

  return ok({ lock, lockPath: writeResult.value, entries, changed });
}
